package vaccinemanagement;


import java.awt.Color;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aadilsaudagar
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    LoadingBar.setForeground(Color.CYAN);
    LoadingBar.setBackground(Color.YELLOW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGrounPanel = new javax.swing.JPanel();
        LoadingBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        LoadingLabel = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGrounPanel.setBackground(new java.awt.Color(51, 255, 255));
        BackGrounPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        BackGrounPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingBar.setBackground(new java.awt.Color(0, 181, 204));
        BackGrounPanel.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 480, 920, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinemanagement/doctors-concept-illustration_114360-1515-removebg-preview.png"))); // NOI18N
        BackGrounPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 600, 320));

        LoadingLabel.setFont(new java.awt.Font("Sathu", 0, 14)); // NOI18N
        LoadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoadingLabel.setText("Loading...");
        BackGrounPanel.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        Name.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Vaccine Mangement System");
        BackGrounPanel.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        LoadingValue.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setText("0%");
        BackGrounPanel.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, -1, -1));

        BackgroundImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccinemanagement/filter.jpeg"))); // NOI18N
        BackgroundImage.setText("jLabel1");
        BackGrounPanel.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 500));

        getContentPane().add(BackGrounPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       SplashScreen sp= new SplashScreen();
       sp.setVisible(true);
        try {
            for(int i=0;i<=100;i++)
            {
                Thread.sleep(100);
                sp.LoadingValue.setText((Integer.toString(i))+"%");
                
                if(i==10)
                {
                    sp.LoadingLabel.setText("Turning on Modules......");
                }
                
                if(i==20)
                {
                    sp.LoadingLabel.setText("Loading on Modules......");
                }
                if(i==50)
                {
                    sp.LoadingLabel.setText("Connecting To Database......");
                }
                
                if(i==70)
                {
                    sp.LoadingLabel.setText("Connection Successful......");
                }
                if(i==80)
                {
                    sp.LoadingLabel.setText("Launching Application......");
                }
                   sp.LoadingBar.setValue(i);
            }
                
            sp.dispose();
            new Welcome2().setVisible(true);
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(sp, e);
        }
               
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGrounPanel;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
